### ISSUE TITLE
Compilation error 'index.d.ts' not found

### ISSUE THREAD

**Issue by gcornut** [unimonkiez/ts-declaration-webpack-plugin#4]
Hello,
I've recently refactor a project, and since then, I've lost the generation of the typescript declaration file.

My webpack build result in an error:
```
ℹ ｢atl｣: Using typescript@3.7.2 from typescript
ℹ ｢atl｣: Using tsconfig.json from /home/gcornut/git/design-system/packages/lumx-react/tsconfig.json
ℹ ｢atl｣: Checking started in a separate process...
ℹ ｢atl｣: Time: 2565ms
error TS6053: File '/home/gcornut/git/design-system/packages/lumx-react/src/index.d.ts' not found.
(node:15471) UnhandledPromiseRejectionWarning: Error: Compiled with errors
    at checkDiagnosticsErrors (/home/gcornut/git/design-system/node_modules/dts-bundle-generator/check-diagnostics-errors.js:20:11)
    at Object.checkProgramDiagnosticsErrors (/home/gcornut/git/design-system/node_modules/dts-bundle-generator/check-diagnostics-errors.js:11:5)
    at Object.compileDts (/home/gcornut/git/design-system/node_modules/dts-bundle-generator/compile-dts.js:43:32)
    at generateDtsBundle (/home/gcornut/git/design-system/node_modules/dts-bundle-generator/bundle-generator.js:33:33)
    at entrypoint.origins.forEach.element (/home/gcornut/git/design-system/node_modules/ts-declaration-webpack-plugin/index.js:25:37)
    at Array.forEach (<anonymous>)
    at compilation.entrypoints.forEach.entrypoint (/home/gcornut/git/design-system/node_modules/ts-declaration-webpack-plugin/index.js:23:36)
    at Map.forEach (<anonymous>)
    at compiler.plugin (/home/gcornut/git/design-system/node_modules/ts-declaration-webpack-plugin/index.js:22:37)
    at _next1 (eval at create (/home/gcornut/git/design-system/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:13:1)
    at _err1 (eval at create (/home/gcornut/git/design-system/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:39:1)
    at Promise.all.catch.then (/home/gcornut/git/design-system/node_modules/copy-webpack-plugin/dist/index.js:90:9)
(node:15471) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:15471) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Done in 24.98s.
```

The `webpack.config.js` that produced this error:
https://github.com/lumapps/design-system/blob/fix/lumx-react-ts-declaration-files/packages/lumx-react/webpack.config.js

Any idea on how I could trace the source of the error?

**Comment by hdmr14** [comment]
I have same issue.
It seems like caused by using outdated `dts-bundle-generator`(`^1.6.1`, latest is `3.3.1`).

Running code below with `1.6.1` and minimal index.ts, the error reproduced. but not reproduced with `3.3.1`.

```
npx dts-bundle-generator -o index.d.ts index.ts
```

I suppose dependencies should be upgraded.

**Comment by gcornut** [comment]
Yes for now I've decided to use a "postbuild" npm script instead:
```
"postbuild": "dts-bundle-generator --no-check --external-types=react --external-imports=moment -o dist/lumx.react.d.ts src/index.ts",
```
https://github.com/lumapps/design-system/blob/a426db410c7466d4d55d48e131aed289e8d6e998/packages/lumx-react/package.json#L114

**Comment by unimonkiez** [comment]
Just updated the dependencies, `v1.2.1` is available to install.
Please check if the issue is fixed.

**Comment by bh3605** [comment]
This is still broken in v1.2.3
